POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Life's good",
    "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
}