PUT http://localhost:3001/api/notes/6180425bd2014194f63ca8c3
Content-Type: application/json

{
    "content": "Las pequeñas cosas y momentos de la vida siempre hay que aprovecharlas",
    "important": false
}
